export const vehicleManufacturesColumns = [
  {
    title: "Вид спецтехники".toUpperCase(),
    dataIndex: "machineType",
    key: "machineType",
  },
  {
    title: "Семейство ТС".toUpperCase(),
    dataIndex: "machineFamily",
    key: "machineFamily",
  },
  {
    title: "Модель ТС".toUpperCase(),
    dataIndex: "machineModel",
    key: "machineModel",
  },
  {
    title: "Заводской номер".toUpperCase(),
    dataIndex: "serialNumber",
    key: "serialNumber",
  },
  {
    title: "Номер шасси".toUpperCase(),
    dataIndex: "chassisNumber",
    key: "chassisNumber",
  },
  {
    title: "Дата подключения".toUpperCase(),
    dataIndex: "connectionDate",
    key: "connectionDate",
  },
];

export const vehicleManufacturesData = [
  {
    key: "1",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
  {
    key: "2",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
  {
    key: "3",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
  {
    key: "4",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
  {
    key: "5",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
  {
    key: "6",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
  {
    key: "7",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
  {
    key: "8",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
  {
    key: "9",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
  {
    key: "10",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
  {
    key: "11",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
  {
    key: "12",
    machineType: "Строительно-дорожная",
    machineFamily: "Гусеничные экскаваторы",
    machineModel: "E330C",
    serialNumber: "XTCTEST0000360515",
    chassisNumber: "XTCTEST0000785344",
    connectionDate: "20.01.2019",
  },
];

export const selectorOptions = [
  { value: "serialNumber", label: "По заводскому номеру" },
  { value: "chassisNumber", label: "По номеру шасси" },
  { value: "vehicleId", label: "По уникальному идентификатору устройства" },
  { value: "vehicleModel", label: "По модели ТС" },
  { value: "pcmNumber", label: "По номеру ПТС / ПСМ" },
];
